<?php
global $ARDUPINMAP_A, $ARDUPINMAP_B, $ARDUPINMAP_C, $ARDUPINMAP_D, $ARDUPINMAP_E ;
$ARDUPINMAP_A = array(
    '0' => array('arduport' => 'DIGITAL I/O 0 (Serial RX)', 'reserved' => 1, 'ethernet' => 0, 'mode' => 'disable', 'logicalId' => 'SerialRX', 'user_authorized' => 0),
    '1' => array('arduport' => 'DIGITAL I/O 1 (Serial TX)', 'reserved' => 1, 'ethernet' => 0, 'mode' => 'disable', 'logicalId' => 'SerialTX', 'user_authorized' => 0),
    '2' => array('arduport' => 'DIGITAL I/O 2 (INT0)', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '3' => array('arduport' => 'DIGITAL I/O 3 (INT1 - PWM)', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '4' => array('arduport' => 'DIGITAL I/O 4', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '5' => array('arduport' => 'DIGITAL I/O 5 (PWM)', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '6' => array('arduport' => 'DIGITAL I/O 6 (PWM)', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '7' => array('arduport' => 'DIGITAL I/O 7', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '8' => array('arduport' => 'DIGITAL I/O 8', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '9' => array('arduport' => 'DIGITAL I/O 9 (PWM)', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '10' => array('arduport' => 'DIGITAL I/O 10 (PWM)', 'reserved' => 0, 'ethernet' => 1, 'user_authorized' => 1),
    '11' => array('arduport' => 'DIGITAL I/O 11 (PWM)', 'reserved' => 0, 'ethernet' => 1, 'user_authorized' => 1),
    '12' => array('arduport' => 'DIGITAL I/O 12', 'reserved' => 0, 'ethernet' => 1, 'user_authorized' => 1),
    '13' => array('arduport' => 'DIGITAL I/O 13 (LED)', 'reserved' => 0, 'ethernet' => 1, 'user_authorized' => 1),

    '14' => array('arduport' => 'ANALOG IN A0', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '15' => array('arduport' => 'ANALOG IN A1', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '16' => array('arduport' => 'ANALOG IN A2', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '17' => array('arduport' => 'ANALOG IN A3', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '18' => array('arduport' => 'ANALOG IN A4', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '19' => array('arduport' => 'ANALOG IN A5', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),

    '20' => array('arduport' => 'CustomValue[0]', 'reserved' => 0, 'user_authorized' => 1),
    '21' => array('arduport' => 'CustomValue[1]', 'reserved' => 0, 'user_authorized' => 1),
    '22' => array('arduport' => 'CustomValue[2]', 'reserved' => 0, 'user_authorized' => 1),
    '23' => array('arduport' => 'CustomValue[3]', 'reserved' => 0, 'user_authorized' => 1),
    '24' => array('arduport' => 'CustomValue[4]', 'reserved' => 0, 'user_authorized' => 1),
    '25' => array('arduport' => 'CustomValue[5]', 'reserved' => 0, 'user_authorized' => 1),
    '26' => array('arduport' => 'CustomValue[6]', 'reserved' => 0, 'user_authorized' => 1),
    '27' => array('arduport' => 'CustomValue[7]', 'reserved' => 0, 'user_authorized' => 1),
    '28' => array('arduport' => 'CustomValue[8]', 'reserved' => 0, 'user_authorized' => 1),
    '29' => array('arduport' => 'CustomValue[9]', 'reserved' => 0, 'user_authorized' => 1),
    '30' => array('arduport' => 'CustomValue[10]', 'reserved' => 0, 'user_authorized' => 1),
    '31' => array('arduport' => 'CustomValue[11]', 'reserved' => 0, 'user_authorized' => 1),
    '32' => array('arduport' => 'CustomValue[12]', 'reserved' => 0, 'user_authorized' => 1),
    '33' => array('arduport' => 'CustomValue[13]', 'reserved' => 0, 'user_authorized' => 1),
    '34' => array('arduport' => 'CustomValue[14]', 'reserved' => 0, 'user_authorized' => 1),
    '35' => array('arduport' => 'CustomValue[15]', 'reserved' => 0, 'user_authorized' => 1),
    '36' => array('arduport' => 'CustomValue[16]', 'reserved' => 0, 'user_authorized' => 1),
    '37' => array('arduport' => 'CustomValue[17]', 'reserved' => 0, 'user_authorized' => 1),
    '38' => array('arduport' => 'CustomValue[18]', 'reserved' => 0, 'user_authorized' => 1),
    '39' => array('arduport' => 'CustomValue[19]', 'reserved' => 0, 'user_authorized' => 1),
    '40' => array('arduport' => 'CustomValue[20]', 'reserved' => 0, 'user_authorized' => 1),
    '41' => array('arduport' => 'CustomValue[21]', 'reserved' => 0, 'user_authorized' => 1),
    '42' => array('arduport' => 'CustomValue[22]', 'reserved' => 0, 'user_authorized' => 1),
    '43' => array('arduport' => 'CustomValue[23]', 'reserved' => 0, 'user_authorized' => 1),
    '44' => array('arduport' => 'CustomValue[24]', 'reserved' => 0, 'user_authorized' => 1),
    '45' => array('arduport' => 'CustomValue[25]', 'reserved' => 0, 'user_authorized' => 1),
    '46' => array('arduport' => 'CustomValue[26]', 'reserved' => 0, 'user_authorized' => 1),
    '47' => array('arduport' => 'CustomValue[27]', 'reserved' => 0, 'user_authorized' => 1),
    '48' => array('arduport' => 'CustomValue[28]', 'reserved' => 0, 'user_authorized' => 1),
    '49' => array('arduport' => 'CustomValue[29]', 'reserved' => 0, 'user_authorized' => 1),
    '50' => array('arduport' => 'CustomValue[30]', 'reserved' => 0, 'user_authorized' => 1),
    '51' => array('arduport' => 'CustomValue[31]', 'reserved' => 0, 'user_authorized' => 1),
    '52' => array('arduport' => 'CustomValue[32]', 'reserved' => 0, 'user_authorized' => 1),
    '53' => array('arduport' => 'CustomValue[33]', 'reserved' => 0, 'user_authorized' => 1),
    '54' => array('arduport' => 'CustomValue[34]', 'reserved' => 0, 'user_authorized' => 1),
    '55' => array('arduport' => 'CustomValue[35]', 'reserved' => 0, 'user_authorized' => 1),
    '56' => array('arduport' => 'CustomValue[36]', 'reserved' => 0, 'user_authorized' => 1),
    '57' => array('arduport' => 'CustomValue[37]', 'reserved' => 0, 'user_authorized' => 1),
    '58' => array('arduport' => 'CustomValue[38]', 'reserved' => 0, 'user_authorized' => 1),
    '59' => array('arduport' => 'CustomValue[39]', 'reserved' => 0, 'user_authorized' => 1),
    '60' => array('arduport' => 'CustomValue[40]', 'reserved' => 0, 'user_authorized' => 1),
    '61' => array('arduport' => 'CustomValue[41]', 'reserved' => 0, 'user_authorized' => 1),
    '62' => array('arduport' => 'CustomValue[42]', 'reserved' => 0, 'user_authorized' => 1),
    '63' => array('arduport' => 'CustomValue[43]', 'reserved' => 0, 'user_authorized' => 1),
    '64' => array('arduport' => 'CustomValue[44]', 'reserved' => 0, 'user_authorized' => 1),
    '65' => array('arduport' => 'CustomValue[45]', 'reserved' => 0, 'user_authorized' => 1),
    '66' => array('arduport' => 'CustomValue[46]', 'reserved' => 0, 'user_authorized' => 1),
    '67' => array('arduport' => 'CustomValue[47]', 'reserved' => 0, 'user_authorized' => 1),
    '68' => array('arduport' => 'CustomValue[48]', 'reserved' => 0, 'user_authorized' => 1),
    '69' => array('arduport' => 'CustomValue[49]', 'reserved' => 0, 'user_authorized' => 1),
    '70' => array('arduport' => 'CustomValue[50]', 'reserved' => 0, 'user_authorized' => 1),
    '71' => array('arduport' => 'CustomValue[51]', 'reserved' => 0, 'user_authorized' => 1),
    '72' => array('arduport' => 'CustomValue[52]', 'reserved' => 0, 'user_authorized' => 1),
    '73' => array('arduport' => 'CustomValue[53]', 'reserved' => 0, 'user_authorized' => 1),
    '74' => array('arduport' => 'CustomValue[54]', 'reserved' => 0, 'user_authorized' => 1),
    '75' => array('arduport' => 'CustomValue[55]', 'reserved' => 0, 'user_authorized' => 1),
    '76' => array('arduport' => 'CustomValue[56]', 'reserved' => 0, 'user_authorized' => 1),
    '77' => array('arduport' => 'CustomValue[57]', 'reserved' => 0, 'user_authorized' => 1),
    '78' => array('arduport' => 'CustomValue[58]', 'reserved' => 0, 'user_authorized' => 1),
    '79' => array('arduport' => 'CustomValue[59]', 'reserved' => 0, 'user_authorized' => 1),
    '80' => array('arduport' => 'CustomValue[60]', 'reserved' => 0, 'user_authorized' => 1),
    '81' => array('arduport' => 'CustomValue[61]', 'reserved' => 0, 'user_authorized' => 1),
    '82' => array('arduport' => 'CustomValue[62]', 'reserved' => 0, 'user_authorized' => 1),
    '83' => array('arduport' => 'CustomValue[63]', 'reserved' => 0, 'user_authorized' => 1),
    '84' => array('arduport' => 'CustomValue[64]', 'reserved' => 0, 'user_authorized' => 1),
    '85' => array('arduport' => 'CustomValue[65]', 'reserved' => 0, 'user_authorized' => 1),
    '86' => array('arduport' => 'CustomValue[66]', 'reserved' => 0, 'user_authorized' => 1),
    '87' => array('arduport' => 'CustomValue[67]', 'reserved' => 0, 'user_authorized' => 1),
    '88' => array('arduport' => 'CustomValue[68]', 'reserved' => 0, 'user_authorized' => 1),
    '89' => array('arduport' => 'CustomValue[69]', 'reserved' => 0, 'user_authorized' => 1),
    '90' => array('arduport' => 'CustomValue[70]', 'reserved' => 0, 'user_authorized' => 1),
    '91' => array('arduport' => 'CustomValue[71]', 'reserved' => 0, 'user_authorized' => 1),
    '92' => array('arduport' => 'CustomValue[72]', 'reserved' => 0, 'user_authorized' => 1),
    '93' => array('arduport' => 'CustomValue[73]', 'reserved' => 0, 'user_authorized' => 1),
    '94' => array('arduport' => 'CustomValue[74]', 'reserved' => 0, 'user_authorized' => 1),
    '95' => array('arduport' => 'CustomValue[75]', 'reserved' => 0, 'user_authorized' => 1),
    '96' => array('arduport' => 'CustomValue[76]', 'reserved' => 0, 'user_authorized' => 1),
    '97' => array('arduport' => 'CustomValue[77]', 'reserved' => 0, 'user_authorized' => 1),
    '98' => array('arduport' => 'CustomValue[78]', 'reserved' => 0, 'user_authorized' => 1),
    '99' => array('arduport' => 'CustomValue[79]', 'reserved' => 0, 'user_authorized' => 1),
    '100' => array('arduport' => 'CustomValue[80]', 'reserved' => 0, 'user_authorized' => 1),
    '101' => array('arduport' => 'CustomValue[81]', 'reserved' => 0, 'user_authorized' => 1),
    '102' => array('arduport' => 'CustomValue[82]', 'reserved' => 0, 'user_authorized' => 1),
    '103' => array('arduport' => 'CustomValue[83]', 'reserved' => 0, 'user_authorized' => 1),
    '104' => array('arduport' => 'CustomValue[84]', 'reserved' => 0, 'user_authorized' => 1),
    '105' => array('arduport' => 'CustomValue[85]', 'reserved' => 0, 'user_authorized' => 1),
    '106' => array('arduport' => 'CustomValue[86]', 'reserved' => 0, 'user_authorized' => 1),
    '107' => array('arduport' => 'CustomValue[87]', 'reserved' => 0, 'user_authorized' => 1),
    '108' => array('arduport' => 'CustomValue[88]', 'reserved' => 0, 'user_authorized' => 1),
    '109' => array('arduport' => 'CustomValue[89]', 'reserved' => 0, 'user_authorized' => 1),
    '110' => array('arduport' => 'CustomValue[90]', 'reserved' => 0, 'user_authorized' => 1),
    '111' => array('arduport' => 'CustomValue[91]', 'reserved' => 0, 'user_authorized' => 1),
    '112' => array('arduport' => 'CustomValue[92]', 'reserved' => 0, 'user_authorized' => 1),
    '113' => array('arduport' => 'CustomValue[93]', 'reserved' => 0, 'user_authorized' => 1),
    '114' => array('arduport' => 'CustomValue[94]', 'reserved' => 0, 'user_authorized' => 1),
    '115' => array('arduport' => 'CustomValue[95]', 'reserved' => 0, 'user_authorized' => 1),
    '116' => array('arduport' => 'CustomValue[96]', 'reserved' => 0, 'user_authorized' => 1),
    '117' => array('arduport' => 'CustomValue[97]', 'reserved' => 0, 'user_authorized' => 1),
    '118' => array('arduport' => 'CustomValue[98]', 'reserved' => 0, 'user_authorized' => 1),
    '119' => array('arduport' => 'CustomValue[99]', 'reserved' => 0, 'user_authorized' => 1),
    '120' => array('arduport' => 'CustomValue[100]', 'reserved' => 0, 'user_authorized' => 1),
    '121' => array('arduport' => 'CustomValue[101]', 'reserved' => 0, 'user_authorized' => 1),
    '122' => array('arduport' => 'CustomValue[102]', 'reserved' => 0, 'user_authorized' => 1),
    '123' => array('arduport' => 'CustomValue[103]', 'reserved' => 0, 'user_authorized' => 1),
    '124' => array('arduport' => 'CustomValue[104]', 'reserved' => 0, 'user_authorized' => 1),
    '125' => array('arduport' => 'CustomValue[105]', 'reserved' => 0, 'user_authorized' => 1),
    '126' => array('arduport' => 'CustomValue[106]', 'reserved' => 0, 'user_authorized' => 1),
    '127' => array('arduport' => 'CustomValue[107]', 'reserved' => 0, 'user_authorized' => 1),
    '128' => array('arduport' => 'CustomValue[108]', 'reserved' => 0, 'user_authorized' => 1),
    '129' => array('arduport' => 'CustomValue[109]', 'reserved' => 0, 'user_authorized' => 1),
    '130' => array('arduport' => 'CustomValue[110]', 'reserved' => 0, 'user_authorized' => 1),
    '131' => array('arduport' => 'CustomValue[111]', 'reserved' => 0, 'user_authorized' => 1),
    '132' => array('arduport' => 'CustomValue[112]', 'reserved' => 0, 'user_authorized' => 1),
    '133' => array('arduport' => 'CustomValue[113]', 'reserved' => 0, 'user_authorized' => 1),
    '134' => array('arduport' => 'CustomValue[114]', 'reserved' => 0, 'user_authorized' => 1),
    '135' => array('arduport' => 'CustomValue[115]', 'reserved' => 0, 'user_authorized' => 1),
    '136' => array('arduport' => 'CustomValue[116]', 'reserved' => 0, 'user_authorized' => 1),
    '137' => array('arduport' => 'CustomValue[117]', 'reserved' => 0, 'user_authorized' => 1),
    '138' => array('arduport' => 'CustomValue[118]', 'reserved' => 0, 'user_authorized' => 1),
    '139' => array('arduport' => 'CustomValue[119]', 'reserved' => 0, 'user_authorized' => 1),
    '140' => array('arduport' => 'CustomValue[120]', 'reserved' => 0, 'user_authorized' => 1),
    '141' => array('arduport' => 'CustomValue[121]', 'reserved' => 0, 'user_authorized' => 1),
    '142' => array('arduport' => 'CustomValue[122]', 'reserved' => 0, 'user_authorized' => 1),
    '143' => array('arduport' => 'CustomValue[123]', 'reserved' => 0, 'user_authorized' => 1),
    '144' => array('arduport' => 'CustomValue[124]', 'reserved' => 0, 'user_authorized' => 1),
    '145' => array('arduport' => 'CustomValue[125]', 'reserved' => 0, 'user_authorized' => 1),
    '146' => array('arduport' => 'CustomValue[126]', 'reserved' => 0, 'user_authorized' => 1),
    '147' => array('arduport' => 'CustomValue[127]', 'reserved' => 0, 'user_authorized' => 1),

    '501' => array('arduport' => 'DHT 1 - Humidité', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '502' => array('arduport' => 'DHT 1 - Température', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '503' => array('arduport' => 'DHT 2 - Humidité', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '504' => array('arduport' => 'DHT 2 - Température', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '505' => array('arduport' => 'DHT 3 - Humidité', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '506' => array('arduport' => 'DHT 3 - Température', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '507' => array('arduport' => 'DHT 4 - Humidité', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '508' => array('arduport' => 'DHT 4 - Température', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '509' => array('arduport' => 'DHT 5 - Humidité', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '510' => array('arduport' => 'DHT 5 - Température', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '511' => array('arduport' => 'DHT 6 - Humidité', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '512' => array('arduport' => 'DHT 6 - Température', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '513' => array('arduport' => 'DHT 7 - Humidité', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '514' => array('arduport' => 'DHT 7 - Température', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '515' => array('arduport' => 'DHT 8 - Humidité', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '516' => array('arduport' => 'DHT 8 - Température', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),

);

$ARDUPINMAP_B = array(
    '0' => array('arduport' => 'DIGITAL I/O 0 (Serial RX0)', 'reserved' => 1, 'ethernet' => 0, 'mode' => 'disable', 'logicalId' => 'SerialRX', 'user_authorized' => 0),
    '1' => array('arduport' => 'DIGITAL I/O 1 (Serial TX0)', 'reserved' => 1, 'ethernet' => 0, 'mode' => 'disable', 'logicalId' => 'SerialTX', 'user_authorized' => 0),
    '2' => array('arduport' => 'DIGITAL I/O 2 (INT0 - PWM)', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '3' => array('arduport' => 'DIGITAL I/O 3 (INT1 - PWM)', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '4' => array('arduport' => 'DIGITAL I/O 4 (PWM)', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '5' => array('arduport' => 'DIGITAL I/O 5 (PWM)', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '6' => array('arduport' => 'DIGITAL I/O 6 (PWM)', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '7' => array('arduport' => 'DIGITAL I/O 7 (PWM)', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '8' => array('arduport' => 'DIGITAL I/O 8 (PWM)', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '9' => array('arduport' => 'DIGITAL I/O 9 (PWM)', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '10' => array('arduport' => 'DIGITAL I/O 10 (PWM)', 'reserved' => 0, 'ethernet' => 1, 'user_authorized' => 1),
    '11' => array('arduport' => 'DIGITAL I/O 11 (PWM)', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '12' => array('arduport' => 'DIGITAL I/O 12 (PWM)', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '13' => array('arduport' => 'DIGITAL I/O 13 (PWM - LED)', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '14' => array('arduport' => 'DIGITAL I/O 14 (Serial TX3)', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '15' => array('arduport' => 'DIGITAL I/O 15 (Serial RX3)', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '16' => array('arduport' => 'DIGITAL I/O 16 (Serial TX2)', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '17' => array('arduport' => 'DIGITAL I/O 17 (Serial RX2)', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '18' => array('arduport' => 'DIGITAL I/O 18 (INT5 - Serial TX1)', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '19' => array('arduport' => 'DIGITAL I/O 19 (INT4 - Serial RX1)', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '20' => array('arduport' => 'DIGITAL I/O 20 (INT3)', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '21' => array('arduport' => 'DIGITAL I/O 21 (INT2)', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '22' => array('arduport' => 'DIGITAL I/O 22', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '23' => array('arduport' => 'DIGITAL I/O 23', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '24' => array('arduport' => 'DIGITAL I/O 24', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '25' => array('arduport' => 'DIGITAL I/O 25', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '26' => array('arduport' => 'DIGITAL I/O 26', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '27' => array('arduport' => 'DIGITAL I/O 27', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '28' => array('arduport' => 'DIGITAL I/O 28', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '29' => array('arduport' => 'DIGITAL I/O 29', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '30' => array('arduport' => 'DIGITAL I/O 30', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '31' => array('arduport' => 'DIGITAL I/O 31', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '32' => array('arduport' => 'DIGITAL I/O 32', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '33' => array('arduport' => 'DIGITAL I/O 33', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '34' => array('arduport' => 'DIGITAL I/O 34', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '35' => array('arduport' => 'DIGITAL I/O 35', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '36' => array('arduport' => 'DIGITAL I/O 36', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '37' => array('arduport' => 'DIGITAL I/O 37', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '38' => array('arduport' => 'DIGITAL I/O 38', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '39' => array('arduport' => 'DIGITAL I/O 39', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '40' => array('arduport' => 'DIGITAL I/O 40', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '41' => array('arduport' => 'DIGITAL I/O 41', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '42' => array('arduport' => 'DIGITAL I/O 42', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '43' => array('arduport' => 'DIGITAL I/O 43', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '44' => array('arduport' => 'DIGITAL I/O 44', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '45' => array('arduport' => 'DIGITAL I/O 45', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '46' => array('arduport' => 'DIGITAL I/O 46 (PWM)', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '47' => array('arduport' => 'DIGITAL I/O 47 (PWM)', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '48' => array('arduport' => 'DIGITAL I/O 48 (PWM)', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '49' => array('arduport' => 'DIGITAL I/O 49', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '50' => array('arduport' => 'DIGITAL I/O 50', 'reserved' => 0, 'ethernet' => 1, 'user_authorized' => 1),
    '51' => array('arduport' => 'DIGITAL I/O 51', 'reserved' => 0, 'ethernet' => 1, 'user_authorized' => 1),
    '52' => array('arduport' => 'DIGITAL I/O 52', 'reserved' => 0, 'ethernet' => 1, 'user_authorized' => 1),
    '53' => array('arduport' => 'DIGITAL I/O 53', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),

    '54' => array('arduport' => 'ANALOG IN A0', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '55' => array('arduport' => 'ANALOG IN A1', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '56' => array('arduport' => 'ANALOG IN A2', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '57' => array('arduport' => 'ANALOG IN A3', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '58' => array('arduport' => 'ANALOG IN A4', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '59' => array('arduport' => 'ANALOG IN A5', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '60' => array('arduport' => 'ANALOG IN A6', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '61' => array('arduport' => 'ANALOG IN A7', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '62' => array('arduport' => 'ANALOG IN A8', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '63' => array('arduport' => 'ANALOG IN A9', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '64' => array('arduport' => 'ANALOG IN A10', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '65' => array('arduport' => 'ANALOG IN A11', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '66' => array('arduport' => 'ANALOG IN A12', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '67' => array('arduport' => 'ANALOG IN A13', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '68' => array('arduport' => 'ANALOG IN A14', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '69' => array('arduport' => 'ANALOG IN A15', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),

    '70' => array('arduport' => 'CustomValue[0]', 'reserved' => 0, 'user_authorized' => 1),
    '71' => array('arduport' => 'CustomValue[1]', 'reserved' => 0, 'user_authorized' => 1),
    '72' => array('arduport' => 'CustomValue[2]', 'reserved' => 0, 'user_authorized' => 1),
    '73' => array('arduport' => 'CustomValue[3]', 'reserved' => 0, 'user_authorized' => 1),
    '74' => array('arduport' => 'CustomValue[4]', 'reserved' => 0, 'user_authorized' => 1),
    '75' => array('arduport' => 'CustomValue[5]', 'reserved' => 0, 'user_authorized' => 1),
    '76' => array('arduport' => 'CustomValue[6]', 'reserved' => 0, 'user_authorized' => 1),
    '77' => array('arduport' => 'CustomValue[7]', 'reserved' => 0, 'user_authorized' => 1),
    '78' => array('arduport' => 'CustomValue[8]', 'reserved' => 0, 'user_authorized' => 1),
    '79' => array('arduport' => 'CustomValue[9]', 'reserved' => 0, 'user_authorized' => 1),
    '80' => array('arduport' => 'CustomValue[10]', 'reserved' => 0, 'user_authorized' => 1),
    '81' => array('arduport' => 'CustomValue[11]', 'reserved' => 0, 'user_authorized' => 1),
    '82' => array('arduport' => 'CustomValue[12]', 'reserved' => 0, 'user_authorized' => 1),
    '83' => array('arduport' => 'CustomValue[13]', 'reserved' => 0, 'user_authorized' => 1),
    '84' => array('arduport' => 'CustomValue[14]', 'reserved' => 0, 'user_authorized' => 1),
    '85' => array('arduport' => 'CustomValue[15]', 'reserved' => 0, 'user_authorized' => 1),
    '86' => array('arduport' => 'CustomValue[16]', 'reserved' => 0, 'user_authorized' => 1),
    '87' => array('arduport' => 'CustomValue[17]', 'reserved' => 0, 'user_authorized' => 1),
    '88' => array('arduport' => 'CustomValue[18]', 'reserved' => 0, 'user_authorized' => 1),
    '89' => array('arduport' => 'CustomValue[19]', 'reserved' => 0, 'user_authorized' => 1),
    '90' => array('arduport' => 'CustomValue[20]', 'reserved' => 0, 'user_authorized' => 1),
    '91' => array('arduport' => 'CustomValue[21]', 'reserved' => 0, 'user_authorized' => 1),
    '92' => array('arduport' => 'CustomValue[22]', 'reserved' => 0, 'user_authorized' => 1),
    '93' => array('arduport' => 'CustomValue[23]', 'reserved' => 0, 'user_authorized' => 1),
    '94' => array('arduport' => 'CustomValue[24]', 'reserved' => 0, 'user_authorized' => 1),
    '95' => array('arduport' => 'CustomValue[25]', 'reserved' => 0, 'user_authorized' => 1),
    '96' => array('arduport' => 'CustomValue[26]', 'reserved' => 0, 'user_authorized' => 1),
    '97' => array('arduport' => 'CustomValue[27]', 'reserved' => 0, 'user_authorized' => 1),
    '98' => array('arduport' => 'CustomValue[28]', 'reserved' => 0, 'user_authorized' => 1),
    '99' => array('arduport' => 'CustomValue[29]', 'reserved' => 0, 'user_authorized' => 1),
    '100' => array('arduport' => 'CustomValue[30]', 'reserved' => 0, 'user_authorized' => 1),
    '101' => array('arduport' => 'CustomValue[31]', 'reserved' => 0, 'user_authorized' => 1),
    '102' => array('arduport' => 'CustomValue[32]', 'reserved' => 0, 'user_authorized' => 1),
    '103' => array('arduport' => 'CustomValue[33]', 'reserved' => 0, 'user_authorized' => 1),
    '104' => array('arduport' => 'CustomValue[34]', 'reserved' => 0, 'user_authorized' => 1),
    '105' => array('arduport' => 'CustomValue[35]', 'reserved' => 0, 'user_authorized' => 1),
    '106' => array('arduport' => 'CustomValue[36]', 'reserved' => 0, 'user_authorized' => 1),
    '107' => array('arduport' => 'CustomValue[37]', 'reserved' => 0, 'user_authorized' => 1),
    '108' => array('arduport' => 'CustomValue[38]', 'reserved' => 0, 'user_authorized' => 1),
    '109' => array('arduport' => 'CustomValue[39]', 'reserved' => 0, 'user_authorized' => 1),
    '110' => array('arduport' => 'CustomValue[40]', 'reserved' => 0, 'user_authorized' => 1),
    '111' => array('arduport' => 'CustomValue[41]', 'reserved' => 0, 'user_authorized' => 1),
    '112' => array('arduport' => 'CustomValue[42]', 'reserved' => 0, 'user_authorized' => 1),
    '113' => array('arduport' => 'CustomValue[43]', 'reserved' => 0, 'user_authorized' => 1),
    '114' => array('arduport' => 'CustomValue[44]', 'reserved' => 0, 'user_authorized' => 1),
    '115' => array('arduport' => 'CustomValue[45]', 'reserved' => 0, 'user_authorized' => 1),
    '116' => array('arduport' => 'CustomValue[46]', 'reserved' => 0, 'user_authorized' => 1),
    '117' => array('arduport' => 'CustomValue[47]', 'reserved' => 0, 'user_authorized' => 1),
    '118' => array('arduport' => 'CustomValue[48]', 'reserved' => 0, 'user_authorized' => 1),
    '119' => array('arduport' => 'CustomValue[49]', 'reserved' => 0, 'user_authorized' => 1),
    '120' => array('arduport' => 'CustomValue[50]', 'reserved' => 0, 'user_authorized' => 1),
    '121' => array('arduport' => 'CustomValue[51]', 'reserved' => 0, 'user_authorized' => 1),
    '122' => array('arduport' => 'CustomValue[52]', 'reserved' => 0, 'user_authorized' => 1),
    '123' => array('arduport' => 'CustomValue[53]', 'reserved' => 0, 'user_authorized' => 1),
    '124' => array('arduport' => 'CustomValue[54]', 'reserved' => 0, 'user_authorized' => 1),
    '125' => array('arduport' => 'CustomValue[55]', 'reserved' => 0, 'user_authorized' => 1),
    '126' => array('arduport' => 'CustomValue[56]', 'reserved' => 0, 'user_authorized' => 1),
    '127' => array('arduport' => 'CustomValue[57]', 'reserved' => 0, 'user_authorized' => 1),
    '128' => array('arduport' => 'CustomValue[58]', 'reserved' => 0, 'user_authorized' => 1),
    '129' => array('arduport' => 'CustomValue[59]', 'reserved' => 0, 'user_authorized' => 1),
    '130' => array('arduport' => 'CustomValue[60]', 'reserved' => 0, 'user_authorized' => 1),
    '131' => array('arduport' => 'CustomValue[61]', 'reserved' => 0, 'user_authorized' => 1),
    '132' => array('arduport' => 'CustomValue[62]', 'reserved' => 0, 'user_authorized' => 1),
    '133' => array('arduport' => 'CustomValue[63]', 'reserved' => 0, 'user_authorized' => 1),
    '134' => array('arduport' => 'CustomValue[64]', 'reserved' => 0, 'user_authorized' => 1),
    '135' => array('arduport' => 'CustomValue[65]', 'reserved' => 0, 'user_authorized' => 1),
    '136' => array('arduport' => 'CustomValue[66]', 'reserved' => 0, 'user_authorized' => 1),
    '137' => array('arduport' => 'CustomValue[67]', 'reserved' => 0, 'user_authorized' => 1),
    '138' => array('arduport' => 'CustomValue[68]', 'reserved' => 0, 'user_authorized' => 1),
    '139' => array('arduport' => 'CustomValue[69]', 'reserved' => 0, 'user_authorized' => 1),
    '140' => array('arduport' => 'CustomValue[70]', 'reserved' => 0, 'user_authorized' => 1),
    '141' => array('arduport' => 'CustomValue[71]', 'reserved' => 0, 'user_authorized' => 1),
    '142' => array('arduport' => 'CustomValue[72]', 'reserved' => 0, 'user_authorized' => 1),
    '143' => array('arduport' => 'CustomValue[73]', 'reserved' => 0, 'user_authorized' => 1),
    '144' => array('arduport' => 'CustomValue[74]', 'reserved' => 0, 'user_authorized' => 1),
    '145' => array('arduport' => 'CustomValue[75]', 'reserved' => 0, 'user_authorized' => 1),
    '146' => array('arduport' => 'CustomValue[76]', 'reserved' => 0, 'user_authorized' => 1),
    '147' => array('arduport' => 'CustomValue[77]', 'reserved' => 0, 'user_authorized' => 1),
    '148' => array('arduport' => 'CustomValue[78]', 'reserved' => 0, 'user_authorized' => 1),
    '149' => array('arduport' => 'CustomValue[79]', 'reserved' => 0, 'user_authorized' => 1),
    '150' => array('arduport' => 'CustomValue[80]', 'reserved' => 0, 'user_authorized' => 1),
    '151' => array('arduport' => 'CustomValue[81]', 'reserved' => 0, 'user_authorized' => 1),
    '152' => array('arduport' => 'CustomValue[82]', 'reserved' => 0, 'user_authorized' => 1),
    '153' => array('arduport' => 'CustomValue[83]', 'reserved' => 0, 'user_authorized' => 1),
    '154' => array('arduport' => 'CustomValue[84]', 'reserved' => 0, 'user_authorized' => 1),
    '155' => array('arduport' => 'CustomValue[85]', 'reserved' => 0, 'user_authorized' => 1),
    '156' => array('arduport' => 'CustomValue[86]', 'reserved' => 0, 'user_authorized' => 1),
    '157' => array('arduport' => 'CustomValue[87]', 'reserved' => 0, 'user_authorized' => 1),
    '158' => array('arduport' => 'CustomValue[88]', 'reserved' => 0, 'user_authorized' => 1),
    '159' => array('arduport' => 'CustomValue[89]', 'reserved' => 0, 'user_authorized' => 1),
    '160' => array('arduport' => 'CustomValue[90]', 'reserved' => 0, 'user_authorized' => 1),
    '161' => array('arduport' => 'CustomValue[91]', 'reserved' => 0, 'user_authorized' => 1),
    '162' => array('arduport' => 'CustomValue[92]', 'reserved' => 0, 'user_authorized' => 1),
    '163' => array('arduport' => 'CustomValue[93]', 'reserved' => 0, 'user_authorized' => 1),
    '164' => array('arduport' => 'CustomValue[94]', 'reserved' => 0, 'user_authorized' => 1),
    '165' => array('arduport' => 'CustomValue[95]', 'reserved' => 0, 'user_authorized' => 1),
    '166' => array('arduport' => 'CustomValue[96]', 'reserved' => 0, 'user_authorized' => 1),
    '167' => array('arduport' => 'CustomValue[97]', 'reserved' => 0, 'user_authorized' => 1),
    '168' => array('arduport' => 'CustomValue[98]', 'reserved' => 0, 'user_authorized' => 1),
    '169' => array('arduport' => 'CustomValue[99]', 'reserved' => 0, 'user_authorized' => 1),
    '170' => array('arduport' => 'CustomValue[100]', 'reserved' => 0, 'user_authorized' => 1),
    '171' => array('arduport' => 'CustomValue[101]', 'reserved' => 0, 'user_authorized' => 1),
    '172' => array('arduport' => 'CustomValue[102]', 'reserved' => 0, 'user_authorized' => 1),
    '173' => array('arduport' => 'CustomValue[103]', 'reserved' => 0, 'user_authorized' => 1),
    '174' => array('arduport' => 'CustomValue[104]', 'reserved' => 0, 'user_authorized' => 1),
    '175' => array('arduport' => 'CustomValue[105]', 'reserved' => 0, 'user_authorized' => 1),
    '176' => array('arduport' => 'CustomValue[106]', 'reserved' => 0, 'user_authorized' => 1),
    '177' => array('arduport' => 'CustomValue[107]', 'reserved' => 0, 'user_authorized' => 1),
    '178' => array('arduport' => 'CustomValue[108]', 'reserved' => 0, 'user_authorized' => 1),
    '179' => array('arduport' => 'CustomValue[109]', 'reserved' => 0, 'user_authorized' => 1),
    '180' => array('arduport' => 'CustomValue[110]', 'reserved' => 0, 'user_authorized' => 1),
    '181' => array('arduport' => 'CustomValue[111]', 'reserved' => 0, 'user_authorized' => 1),
    '182' => array('arduport' => 'CustomValue[112]', 'reserved' => 0, 'user_authorized' => 1),
    '183' => array('arduport' => 'CustomValue[113]', 'reserved' => 0, 'user_authorized' => 1),
    '184' => array('arduport' => 'CustomValue[114]', 'reserved' => 0, 'user_authorized' => 1),
    '185' => array('arduport' => 'CustomValue[115]', 'reserved' => 0, 'user_authorized' => 1),
    '186' => array('arduport' => 'CustomValue[116]', 'reserved' => 0, 'user_authorized' => 1),
    '187' => array('arduport' => 'CustomValue[117]', 'reserved' => 0, 'user_authorized' => 1),
    '188' => array('arduport' => 'CustomValue[118]', 'reserved' => 0, 'user_authorized' => 1),
    '189' => array('arduport' => 'CustomValue[119]', 'reserved' => 0, 'user_authorized' => 1),
    '190' => array('arduport' => 'CustomValue[120]', 'reserved' => 0, 'user_authorized' => 1),
    '191' => array('arduport' => 'CustomValue[121]', 'reserved' => 0, 'user_authorized' => 1),
    '192' => array('arduport' => 'CustomValue[122]', 'reserved' => 0, 'user_authorized' => 1),
    '193' => array('arduport' => 'CustomValue[123]', 'reserved' => 0, 'user_authorized' => 1),
    '194' => array('arduport' => 'CustomValue[124]', 'reserved' => 0, 'user_authorized' => 1),
    '195' => array('arduport' => 'CustomValue[125]', 'reserved' => 0, 'user_authorized' => 1),
    '196' => array('arduport' => 'CustomValue[126]', 'reserved' => 0, 'user_authorized' => 1),
    '197' => array('arduport' => 'CustomValue[127]', 'reserved' => 0, 'user_authorized' => 1),

    '501' => array('arduport' => 'DHT 1 - Humidité', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '502' => array('arduport' => 'DHT 1 - Température', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '503' => array('arduport' => 'DHT 2 - Humidité', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '504' => array('arduport' => 'DHT 2 - Température', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '505' => array('arduport' => 'DHT 3 - Humidité', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '506' => array('arduport' => 'DHT 3 - Température', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '507' => array('arduport' => 'DHT 4 - Humidité', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '508' => array('arduport' => 'DHT 4 - Température', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '509' => array('arduport' => 'DHT 5 - Humidité', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '510' => array('arduport' => 'DHT 5 - Température', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '511' => array('arduport' => 'DHT 6 - Humidité', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '512' => array('arduport' => 'DHT 6 - Température', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '513' => array('arduport' => 'DHT 7 - Humidité', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '514' => array('arduport' => 'DHT 7 - Température', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '515' => array('arduport' => 'DHT 8 - Humidité', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '516' => array('arduport' => 'DHT 8 - Température', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
);

$ARDUPINMAP_C = array(
    '0' => array('arduport' => 'DIGITAL I/O 0 (Serial RX0)', 'reserved' => 1, 'ethernet' => 0, 'mode' => 'disable', 'logicalId' => 'SerialRX', 'user_authorized' => 0),
    '1' => array('arduport' => 'DIGITAL I/O 1 (Serial TX0)', 'reserved' => 1, 'ethernet' => 0, 'mode' => 'disable', 'logicalId' => 'SerialTX', 'user_authorized' => 0),
    '2' => array('arduport' => 'DIGITAL I/O 2 (PWM)', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '3' => array('arduport' => 'DIGITAL I/O 3 (PWM)', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '4' => array('arduport' => 'DIGITAL I/O 4 (PWM)', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '5' => array('arduport' => 'DIGITAL I/O 5 (PWM)', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '6' => array('arduport' => 'DIGITAL I/O 6 (PWM)', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '7' => array('arduport' => 'DIGITAL I/O 7 (PWM)', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '8' => array('arduport' => 'DIGITAL I/O 8 (PWM)', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '9' => array('arduport' => 'DIGITAL I/O 9 (PWM)', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '10' => array('arduport' => 'DIGITAL I/O 10 (PWM)', 'reserved' => 0, 'ethernet' => 1, 'user_authorized' => 1),
    '11' => array('arduport' => 'DIGITAL I/O 11 (PWM)', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '12' => array('arduport' => 'DIGITAL I/O 12 (PWM)', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '13' => array('arduport' => 'DIGITAL I/O 13 (PWM - LED)', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '14' => array('arduport' => 'DIGITAL I/O 14 (Serial TX3)', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '15' => array('arduport' => 'DIGITAL I/O 15 (Serial RX3)', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '16' => array('arduport' => 'DIGITAL I/O 16 (Serial TX2)', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '17' => array('arduport' => 'DIGITAL I/O 17 (Serial RX2)', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '18' => array('arduport' => 'DIGITAL I/O 18 (Serial TX1)', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '19' => array('arduport' => 'DIGITAL I/O 19 (Serial RX1)', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '20' => array('arduport' => 'DIGITAL I/O 20', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '21' => array('arduport' => 'DIGITAL I/O 21', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '22' => array('arduport' => 'DIGITAL I/O 22', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '23' => array('arduport' => 'DIGITAL I/O 23', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '24' => array('arduport' => 'DIGITAL I/O 24', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '25' => array('arduport' => 'DIGITAL I/O 25', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '26' => array('arduport' => 'DIGITAL I/O 26', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '27' => array('arduport' => 'DIGITAL I/O 27', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '28' => array('arduport' => 'DIGITAL I/O 28', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '29' => array('arduport' => 'DIGITAL I/O 29', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '30' => array('arduport' => 'DIGITAL I/O 30', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '31' => array('arduport' => 'DIGITAL I/O 31', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '32' => array('arduport' => 'DIGITAL I/O 32', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '33' => array('arduport' => 'DIGITAL I/O 33', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '34' => array('arduport' => 'DIGITAL I/O 34', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '35' => array('arduport' => 'DIGITAL I/O 35', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '36' => array('arduport' => 'DIGITAL I/O 36', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '37' => array('arduport' => 'DIGITAL I/O 37', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '38' => array('arduport' => 'DIGITAL I/O 38', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '39' => array('arduport' => 'DIGITAL I/O 39', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '40' => array('arduport' => 'DIGITAL I/O 40', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '41' => array('arduport' => 'DIGITAL I/O 41', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '42' => array('arduport' => 'DIGITAL I/O 42', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '43' => array('arduport' => 'DIGITAL I/O 43', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '44' => array('arduport' => 'DIGITAL I/O 44', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '45' => array('arduport' => 'DIGITAL I/O 45', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '46' => array('arduport' => 'DIGITAL I/O 46 (PWM)', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '47' => array('arduport' => 'DIGITAL I/O 47 (PWM)', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '48' => array('arduport' => 'DIGITAL I/O 48 (PWM)', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '49' => array('arduport' => 'DIGITAL I/O 49', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '50' => array('arduport' => 'DIGITAL I/O 50', 'reserved' => 0, 'ethernet' => 1, 'user_authorized' => 1),
    '51' => array('arduport' => 'DIGITAL I/O 51', 'reserved' => 0, 'ethernet' => 1, 'user_authorized' => 1),
    '52' => array('arduport' => 'DIGITAL I/O 52', 'reserved' => 0, 'ethernet' => 1, 'user_authorized' => 1),
    '53' => array('arduport' => 'DIGITAL I/O 53', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),

    '54' => array('arduport' => 'ANALOG IN A0', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '55' => array('arduport' => 'ANALOG IN A1', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '56' => array('arduport' => 'ANALOG IN A2', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '57' => array('arduport' => 'ANALOG IN A3', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '58' => array('arduport' => 'ANALOG IN A4', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '59' => array('arduport' => 'ANALOG IN A5', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '60' => array('arduport' => 'ANALOG IN A6', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '61' => array('arduport' => 'ANALOG IN A7', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '62' => array('arduport' => 'ANALOG IN A8', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '63' => array('arduport' => 'ANALOG IN A9', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '64' => array('arduport' => 'ANALOG IN A10', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '65' => array('arduport' => 'ANALOG IN A11', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '66' => array('arduport' => 'ANALOG OUT DAC0', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '67' => array('arduport' => 'ANALOG OUT DAC1', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),

    '68' => array('arduport' => 'CustomValue[0]', 'reserved' => 0, 'user_authorized' => 1),
    '69' => array('arduport' => 'CustomValue[1]', 'reserved' => 0, 'user_authorized' => 1),
    '70' => array('arduport' => 'CustomValue[2]', 'reserved' => 0, 'user_authorized' => 1),
    '71' => array('arduport' => 'CustomValue[3]', 'reserved' => 0, 'user_authorized' => 1),
    '72' => array('arduport' => 'CustomValue[4]', 'reserved' => 0, 'user_authorized' => 1),
    '73' => array('arduport' => 'CustomValue[5]', 'reserved' => 0, 'user_authorized' => 1),
    '74' => array('arduport' => 'CustomValue[6]', 'reserved' => 0, 'user_authorized' => 1),
    '75' => array('arduport' => 'CustomValue[7]', 'reserved' => 0, 'user_authorized' => 1),
    '76' => array('arduport' => 'CustomValue[8]', 'reserved' => 0, 'user_authorized' => 1),
    '77' => array('arduport' => 'CustomValue[9]', 'reserved' => 0, 'user_authorized' => 1),
    '78' => array('arduport' => 'CustomValue[10]', 'reserved' => 0, 'user_authorized' => 1),
    '79' => array('arduport' => 'CustomValue[11]', 'reserved' => 0, 'user_authorized' => 1),
    '80' => array('arduport' => 'CustomValue[12]', 'reserved' => 0, 'user_authorized' => 1),
    '81' => array('arduport' => 'CustomValue[13]', 'reserved' => 0, 'user_authorized' => 1),
    '82' => array('arduport' => 'CustomValue[14]', 'reserved' => 0, 'user_authorized' => 1),
    '83' => array('arduport' => 'CustomValue[15]', 'reserved' => 0, 'user_authorized' => 1),
    '84' => array('arduport' => 'CustomValue[16]', 'reserved' => 0, 'user_authorized' => 1),
    '85' => array('arduport' => 'CustomValue[17]', 'reserved' => 0, 'user_authorized' => 1),
    '86' => array('arduport' => 'CustomValue[18]', 'reserved' => 0, 'user_authorized' => 1),
    '87' => array('arduport' => 'CustomValue[19]', 'reserved' => 0, 'user_authorized' => 1),
    '88' => array('arduport' => 'CustomValue[20]', 'reserved' => 0, 'user_authorized' => 1),
    '89' => array('arduport' => 'CustomValue[21]', 'reserved' => 0, 'user_authorized' => 1),
    '90' => array('arduport' => 'CustomValue[22]', 'reserved' => 0, 'user_authorized' => 1),
    '91' => array('arduport' => 'CustomValue[23]', 'reserved' => 0, 'user_authorized' => 1),
    '92' => array('arduport' => 'CustomValue[24]', 'reserved' => 0, 'user_authorized' => 1),
    '93' => array('arduport' => 'CustomValue[25]', 'reserved' => 0, 'user_authorized' => 1),
    '94' => array('arduport' => 'CustomValue[26]', 'reserved' => 0, 'user_authorized' => 1),
    '95' => array('arduport' => 'CustomValue[27]', 'reserved' => 0, 'user_authorized' => 1),
    '96' => array('arduport' => 'CustomValue[28]', 'reserved' => 0, 'user_authorized' => 1),
    '97' => array('arduport' => 'CustomValue[29]', 'reserved' => 0, 'user_authorized' => 1),
    '98' => array('arduport' => 'CustomValue[30]', 'reserved' => 0, 'user_authorized' => 1),
    '99' => array('arduport' => 'CustomValue[31]', 'reserved' => 0, 'user_authorized' => 1),
    '100' => array('arduport' => 'CustomValue[32]', 'reserved' => 0, 'user_authorized' => 1),
    '101' => array('arduport' => 'CustomValue[33]', 'reserved' => 0, 'user_authorized' => 1),
    '102' => array('arduport' => 'CustomValue[34]', 'reserved' => 0, 'user_authorized' => 1),
    '103' => array('arduport' => 'CustomValue[35]', 'reserved' => 0, 'user_authorized' => 1),
    '104' => array('arduport' => 'CustomValue[36]', 'reserved' => 0, 'user_authorized' => 1),
    '105' => array('arduport' => 'CustomValue[37]', 'reserved' => 0, 'user_authorized' => 1),
    '106' => array('arduport' => 'CustomValue[38]', 'reserved' => 0, 'user_authorized' => 1),
    '107' => array('arduport' => 'CustomValue[39]', 'reserved' => 0, 'user_authorized' => 1),
    '108' => array('arduport' => 'CustomValue[40]', 'reserved' => 0, 'user_authorized' => 1),
    '109' => array('arduport' => 'CustomValue[41]', 'reserved' => 0, 'user_authorized' => 1),
    '110' => array('arduport' => 'CustomValue[42]', 'reserved' => 0, 'user_authorized' => 1),
    '111' => array('arduport' => 'CustomValue[43]', 'reserved' => 0, 'user_authorized' => 1),
    '112' => array('arduport' => 'CustomValue[44]', 'reserved' => 0, 'user_authorized' => 1),
    '113' => array('arduport' => 'CustomValue[45]', 'reserved' => 0, 'user_authorized' => 1),
    '114' => array('arduport' => 'CustomValue[46]', 'reserved' => 0, 'user_authorized' => 1),
    '115' => array('arduport' => 'CustomValue[47]', 'reserved' => 0, 'user_authorized' => 1),
    '116' => array('arduport' => 'CustomValue[48]', 'reserved' => 0, 'user_authorized' => 1),
    '117' => array('arduport' => 'CustomValue[49]', 'reserved' => 0, 'user_authorized' => 1),
    '118' => array('arduport' => 'CustomValue[50]', 'reserved' => 0, 'user_authorized' => 1),
    '119' => array('arduport' => 'CustomValue[51]', 'reserved' => 0, 'user_authorized' => 1),
    '120' => array('arduport' => 'CustomValue[52]', 'reserved' => 0, 'user_authorized' => 1),
    '121' => array('arduport' => 'CustomValue[53]', 'reserved' => 0, 'user_authorized' => 1),
    '122' => array('arduport' => 'CustomValue[54]', 'reserved' => 0, 'user_authorized' => 1),
    '123' => array('arduport' => 'CustomValue[55]', 'reserved' => 0, 'user_authorized' => 1),
    '124' => array('arduport' => 'CustomValue[56]', 'reserved' => 0, 'user_authorized' => 1),
    '125' => array('arduport' => 'CustomValue[57]', 'reserved' => 0, 'user_authorized' => 1),
    '126' => array('arduport' => 'CustomValue[58]', 'reserved' => 0, 'user_authorized' => 1),
    '127' => array('arduport' => 'CustomValue[59]', 'reserved' => 0, 'user_authorized' => 1),
    '128' => array('arduport' => 'CustomValue[60]', 'reserved' => 0, 'user_authorized' => 1),
    '129' => array('arduport' => 'CustomValue[61]', 'reserved' => 0, 'user_authorized' => 1),
    '130' => array('arduport' => 'CustomValue[62]', 'reserved' => 0, 'user_authorized' => 1),
    '131' => array('arduport' => 'CustomValue[63]', 'reserved' => 0, 'user_authorized' => 1),
    '132' => array('arduport' => 'CustomValue[64]', 'reserved' => 0, 'user_authorized' => 1),
    '133' => array('arduport' => 'CustomValue[65]', 'reserved' => 0, 'user_authorized' => 1),
    '134' => array('arduport' => 'CustomValue[66]', 'reserved' => 0, 'user_authorized' => 1),
    '135' => array('arduport' => 'CustomValue[67]', 'reserved' => 0, 'user_authorized' => 1),
    '136' => array('arduport' => 'CustomValue[68]', 'reserved' => 0, 'user_authorized' => 1),
    '137' => array('arduport' => 'CustomValue[69]', 'reserved' => 0, 'user_authorized' => 1),
    '138' => array('arduport' => 'CustomValue[70]', 'reserved' => 0, 'user_authorized' => 1),
    '139' => array('arduport' => 'CustomValue[71]', 'reserved' => 0, 'user_authorized' => 1),
    '140' => array('arduport' => 'CustomValue[72]', 'reserved' => 0, 'user_authorized' => 1),
    '141' => array('arduport' => 'CustomValue[73]', 'reserved' => 0, 'user_authorized' => 1),
    '142' => array('arduport' => 'CustomValue[74]', 'reserved' => 0, 'user_authorized' => 1),
    '143' => array('arduport' => 'CustomValue[75]', 'reserved' => 0, 'user_authorized' => 1),
    '144' => array('arduport' => 'CustomValue[76]', 'reserved' => 0, 'user_authorized' => 1),
    '145' => array('arduport' => 'CustomValue[77]', 'reserved' => 0, 'user_authorized' => 1),
    '146' => array('arduport' => 'CustomValue[78]', 'reserved' => 0, 'user_authorized' => 1),
    '147' => array('arduport' => 'CustomValue[79]', 'reserved' => 0, 'user_authorized' => 1),
    '148' => array('arduport' => 'CustomValue[80]', 'reserved' => 0, 'user_authorized' => 1),
    '149' => array('arduport' => 'CustomValue[81]', 'reserved' => 0, 'user_authorized' => 1),
    '150' => array('arduport' => 'CustomValue[82]', 'reserved' => 0, 'user_authorized' => 1),
    '151' => array('arduport' => 'CustomValue[83]', 'reserved' => 0, 'user_authorized' => 1),
    '152' => array('arduport' => 'CustomValue[84]', 'reserved' => 0, 'user_authorized' => 1),
    '153' => array('arduport' => 'CustomValue[85]', 'reserved' => 0, 'user_authorized' => 1),
    '154' => array('arduport' => 'CustomValue[86]', 'reserved' => 0, 'user_authorized' => 1),
    '155' => array('arduport' => 'CustomValue[87]', 'reserved' => 0, 'user_authorized' => 1),
    '156' => array('arduport' => 'CustomValue[88]', 'reserved' => 0, 'user_authorized' => 1),
    '157' => array('arduport' => 'CustomValue[89]', 'reserved' => 0, 'user_authorized' => 1),
    '158' => array('arduport' => 'CustomValue[90]', 'reserved' => 0, 'user_authorized' => 1),
    '159' => array('arduport' => 'CustomValue[91]', 'reserved' => 0, 'user_authorized' => 1),
    '160' => array('arduport' => 'CustomValue[92]', 'reserved' => 0, 'user_authorized' => 1),
    '161' => array('arduport' => 'CustomValue[93]', 'reserved' => 0, 'user_authorized' => 1),
    '162' => array('arduport' => 'CustomValue[94]', 'reserved' => 0, 'user_authorized' => 1),
    '163' => array('arduport' => 'CustomValue[95]', 'reserved' => 0, 'user_authorized' => 1),
    '164' => array('arduport' => 'CustomValue[96]', 'reserved' => 0, 'user_authorized' => 1),
    '165' => array('arduport' => 'CustomValue[97]', 'reserved' => 0, 'user_authorized' => 1),
    '166' => array('arduport' => 'CustomValue[98]', 'reserved' => 0, 'user_authorized' => 1),
    '167' => array('arduport' => 'CustomValue[99]', 'reserved' => 0, 'user_authorized' => 1),
    '168' => array('arduport' => 'CustomValue[100]', 'reserved' => 0, 'user_authorized' => 1),
    '169' => array('arduport' => 'CustomValue[101]', 'reserved' => 0, 'user_authorized' => 1),
    '170' => array('arduport' => 'CustomValue[102]', 'reserved' => 0, 'user_authorized' => 1),
    '171' => array('arduport' => 'CustomValue[103]', 'reserved' => 0, 'user_authorized' => 1),
    '172' => array('arduport' => 'CustomValue[104]', 'reserved' => 0, 'user_authorized' => 1),
    '173' => array('arduport' => 'CustomValue[105]', 'reserved' => 0, 'user_authorized' => 1),
    '174' => array('arduport' => 'CustomValue[106]', 'reserved' => 0, 'user_authorized' => 1),
    '175' => array('arduport' => 'CustomValue[107]', 'reserved' => 0, 'user_authorized' => 1),
    '176' => array('arduport' => 'CustomValue[108]', 'reserved' => 0, 'user_authorized' => 1),
    '177' => array('arduport' => 'CustomValue[109]', 'reserved' => 0, 'user_authorized' => 1),
    '178' => array('arduport' => 'CustomValue[110]', 'reserved' => 0, 'user_authorized' => 1),
    '179' => array('arduport' => 'CustomValue[111]', 'reserved' => 0, 'user_authorized' => 1),
    '180' => array('arduport' => 'CustomValue[112]', 'reserved' => 0, 'user_authorized' => 1),
    '181' => array('arduport' => 'CustomValue[113]', 'reserved' => 0, 'user_authorized' => 1),
    '182' => array('arduport' => 'CustomValue[114]', 'reserved' => 0, 'user_authorized' => 1),
    '183' => array('arduport' => 'CustomValue[115]', 'reserved' => 0, 'user_authorized' => 1),
    '184' => array('arduport' => 'CustomValue[116]', 'reserved' => 0, 'user_authorized' => 1),
    '185' => array('arduport' => 'CustomValue[117]', 'reserved' => 0, 'user_authorized' => 1),
    '186' => array('arduport' => 'CustomValue[118]', 'reserved' => 0, 'user_authorized' => 1),
    '187' => array('arduport' => 'CustomValue[119]', 'reserved' => 0, 'user_authorized' => 1),
    '188' => array('arduport' => 'CustomValue[120]', 'reserved' => 0, 'user_authorized' => 1),
    '189' => array('arduport' => 'CustomValue[121]', 'reserved' => 0, 'user_authorized' => 1),
    '190' => array('arduport' => 'CustomValue[122]', 'reserved' => 0, 'user_authorized' => 1),
    '191' => array('arduport' => 'CustomValue[123]', 'reserved' => 0, 'user_authorized' => 1),
    '192' => array('arduport' => 'CustomValue[124]', 'reserved' => 0, 'user_authorized' => 1),
    '193' => array('arduport' => 'CustomValue[125]', 'reserved' => 0, 'user_authorized' => 1),
    '194' => array('arduport' => 'CustomValue[126]', 'reserved' => 0, 'user_authorized' => 1),
    '195' => array('arduport' => 'CustomValue[127]', 'reserved' => 0, 'user_authorized' => 1),


    '501' => array('arduport' => 'DHT 1 - Humidité', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '502' => array('arduport' => 'DHT 1 - Température', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '503' => array('arduport' => 'DHT 2 - Humidité', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '504' => array('arduport' => 'DHT 2 - Température', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '505' => array('arduport' => 'DHT 3 - Humidité', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '506' => array('arduport' => 'DHT 3 - Température', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '507' => array('arduport' => 'DHT 4 - Humidité', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '508' => array('arduport' => 'DHT 4 - Température', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '509' => array('arduport' => 'DHT 5 - Humidité', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '510' => array('arduport' => 'DHT 5 - Température', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '511' => array('arduport' => 'DHT 6 - Humidité', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '512' => array('arduport' => 'DHT 6 - Température', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '513' => array('arduport' => 'DHT 7 - Humidité', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '514' => array('arduport' => 'DHT 7 - Température', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '515' => array('arduport' => 'DHT 8 - Humidité', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '516' => array('arduport' => 'DHT 8 - Température', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
);

$ARDUPINMAP_D = array(
    '0' => array('arduport' => '0 ', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '1' => array('arduport' => '1', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '2' => array('arduport' => '2', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '3' => array('arduport' => '3', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '4' => array('arduport' => '1004', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '5' => array('arduport' => '1005', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '6' => array('arduport' => '6', 'reserved' => 1, 'ethernet' => 1, 'user_authorized' => 1),
    '7' => array('arduport' => '7', 'reserved' => 1, 'ethernet' => 1, 'user_authorized' => 1),
    '8' => array('arduport' => '8', 'reserved' => 1, 'ethernet' => 1, 'user_authorized' => 1),
    '9' => array('arduport' => '9', 'reserved' => 1, 'ethernet' => 1, 'user_authorized' => 1),
    '10' => array('arduport' => '10', 'reserved' => 1, 'ethernet' => 1, 'user_authorized' => 1),
    '11' => array('arduport' => '11', 'reserved' => 1, 'ethernet' => 1, 'user_authorized' => 1),
    '12' => array('arduport' => '1012', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '13' => array('arduport' => '1013', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '14' => array('arduport' => '1014', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),

    '15' => array('arduport' => 'ADC', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),

    '16' => array('arduport' => 'CustomValue[0]', 'reserved' => 0, 'user_authorized' => 1),
    '17' => array('arduport' => 'CustomValue[1]', 'reserved' => 0, 'user_authorized' => 1),
    '18' => array('arduport' => 'CustomValue[2]', 'reserved' => 0, 'user_authorized' => 1),
    '19' => array('arduport' => 'CustomValue[3]', 'reserved' => 0, 'user_authorized' => 1),
    '20' => array('arduport' => 'CustomValue[4]', 'reserved' => 0, 'user_authorized' => 1),
    '21' => array('arduport' => 'CustomValue[5]', 'reserved' => 0, 'user_authorized' => 1),
    '22' => array('arduport' => 'CustomValue[6]', 'reserved' => 0, 'user_authorized' => 1),
    '23' => array('arduport' => 'CustomValue[7]', 'reserved' => 0, 'user_authorized' => 1),
    '24' => array('arduport' => 'CustomValue[8]', 'reserved' => 0, 'user_authorized' => 1),
    '25' => array('arduport' => 'CustomValue[9]', 'reserved' => 0, 'user_authorized' => 1),
    '26' => array('arduport' => 'CustomValue[10]', 'reserved' => 0, 'user_authorized' => 1),
    '27' => array('arduport' => 'CustomValue[11]', 'reserved' => 0, 'user_authorized' => 1),
    '28' => array('arduport' => 'CustomValue[12]', 'reserved' => 0, 'user_authorized' => 1),
    '29' => array('arduport' => 'CustomValue[13]', 'reserved' => 0, 'user_authorized' => 1),
    '30' => array('arduport' => 'CustomValue[14]', 'reserved' => 0, 'user_authorized' => 1),
    '31' => array('arduport' => 'CustomValue[15]', 'reserved' => 0, 'user_authorized' => 1),

    '501' => array('arduport' => 'DHT 1 - Humidité', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '502' => array('arduport' => 'DHT 1 - Température', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '503' => array('arduport' => 'DHT 2 - Humidité', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '504' => array('arduport' => 'DHT 2 - Température', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '505' => array('arduport' => 'DHT 3 - Humidité', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '506' => array('arduport' => 'DHT 3 - Température', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '507' => array('arduport' => 'DHT 4 - Humidité', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '508' => array('arduport' => 'DHT 4 - Température', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '509' => array('arduport' => 'DHT 5 - Humidité', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '510' => array('arduport' => 'DHT 5 - Température', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '511' => array('arduport' => 'DHT 6 - Humidité', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '512' => array('arduport' => 'DHT 6 - Température', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '513' => array('arduport' => 'DHT 7 - Humidité', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '514' => array('arduport' => 'DHT 7 - Température', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '515' => array('arduport' => 'DHT 8 - Humidité', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '516' => array('arduport' => 'DHT 8 - Température', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),

);

$ARDUPINMAP_E = array( // WeMOS D1 MINI
    '0' => array('arduport' => 'D3 /!\ (HIGH run / LOW flash)', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '1' => array('arduport' => 'TX', 'reserved' => 1, 'ethernet' => 1, 'user_authorized' => 1),
    '2' => array('arduport' => 'D4 /!\ (SD Mode Select)', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '3' => array('arduport' => 'RX', 'reserved' => 1, 'ethernet' => 1, 'user_authorized' => 1),
    '4' => array('arduport' => 'D2', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '5' => array('arduport' => 'D1', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '6' => array('arduport' => 'N/A', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '7' => array('arduport' => 'N/A', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '8' => array('arduport' => 'N/A', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '9' => array('arduport' => 'N/A', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '10' => array('arduport' => 'N/A', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '11' => array('arduport' => 'N/A', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '12' => array('arduport' => 'D6', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '13' => array('arduport' => 'D7', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '14' => array('arduport' => 'D5', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '15' => array('arduport' => 'D8', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),
    '16' => array('arduport' => 'D0', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),

    '17' => array('arduport' => 'A0 ( ! 3.3V Max ! )', 'reserved' => 0, 'ethernet' => 0, 'user_authorized' => 1),

    '18' => array('arduport' => 'CustomValue[0]', 'reserved' => 0, 'user_authorized' => 1),
    '19' => array('arduport' => 'CustomValue[1]', 'reserved' => 0, 'user_authorized' => 1),
    '20' => array('arduport' => 'CustomValue[2]', 'reserved' => 0, 'user_authorized' => 1),
    '21' => array('arduport' => 'CustomValue[3]', 'reserved' => 0, 'user_authorized' => 1),
    '22' => array('arduport' => 'CustomValue[4]', 'reserved' => 0, 'user_authorized' => 1),
    '23' => array('arduport' => 'CustomValue[5]', 'reserved' => 0, 'user_authorized' => 1),
    '24' => array('arduport' => 'CustomValue[6]', 'reserved' => 0, 'user_authorized' => 1),
    '25' => array('arduport' => 'CustomValue[7]', 'reserved' => 0, 'user_authorized' => 1),
    '26' => array('arduport' => 'CustomValue[8]', 'reserved' => 0, 'user_authorized' => 1),
    '27' => array('arduport' => 'CustomValue[9]', 'reserved' => 0, 'user_authorized' => 1),
    '28' => array('arduport' => 'CustomValue[10]', 'reserved' => 0, 'user_authorized' => 1),
    '29' => array('arduport' => 'CustomValue[11]', 'reserved' => 0, 'user_authorized' => 1),
    '30' => array('arduport' => 'CustomValue[12]', 'reserved' => 0, 'user_authorized' => 1),
    '31' => array('arduport' => 'CustomValue[13]', 'reserved' => 0, 'user_authorized' => 1),
    '32' => array('arduport' => 'CustomValue[14]', 'reserved' => 0, 'user_authorized' => 1),
    '33' => array('arduport' => 'CustomValue[15]', 'reserved' => 0, 'user_authorized' => 1),

    '501' => array('arduport' => 'DHT 1 - Humidité', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '502' => array('arduport' => 'DHT 1 - Température', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '503' => array('arduport' => 'DHT 2 - Humidité', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '504' => array('arduport' => 'DHT 2 - Température', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '505' => array('arduport' => 'DHT 3 - Humidité', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '506' => array('arduport' => 'DHT 3 - Température', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '507' => array('arduport' => 'DHT 4 - Humidité', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '508' => array('arduport' => 'DHT 4 - Température', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '509' => array('arduport' => 'DHT 5 - Humidité', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '510' => array('arduport' => 'DHT 5 - Température', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '511' => array('arduport' => 'DHT 6 - Humidité', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '512' => array('arduport' => 'DHT 6 - Température', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '513' => array('arduport' => 'DHT 7 - Humidité', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '514' => array('arduport' => 'DHT 7 - Température', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '515' => array('arduport' => 'DHT 8 - Humidité', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),
    '516' => array('arduport' => 'DHT 8 - Température', 'reserved' => 1, 'ethernet' => 0, 'user_authorized' => 1),

);
