Ce plugin permet de profiter de la connectivité de l'Arduino (Uno, Mega, etc... Processeur 328 minimum) directement depuis Jeedom. Une fois installé et l'Arduino programmé vous pourrez interagir avec les entrées/sorties Digitales, Entrées analogiques et Sorties PWM. La programmation de l'Arduino intègre un décodeur pour piloter les modules radio 433MHz (Protocoles Low-Cost Tristates, Home-easy, Chacon DIO) et la gestion des sondes DHT (DHT11 et DHT22). Les PIN Virtuelles permettent à vos propres codes de communiquer avec Jeedom après leur ajout au sketch principal.

=== Rôle du plugin (démon) ===
Le plugin collecte les commandes de vos équipements Arduidom pour les envoyer à l'Arduino, reçoit les infos de l'Arduino pour actualisé vos état d'équipement. Il reçoit, convertit et historie les codes radio. Il intègre le démon « push » permettant un envoi/retour très réactif de vos commandes.

=== Rôle du "sketch" ===
L'arduino, petit microcontrôleur, doit être programmé avec le sketch fourni dans le plugin. Ce sketch contient le protocole d'échange avec le plugin Arduidom, le décodeur Radio, la gestion DHT et une section dédiée à vos code perso à la fin du sketch. Comme vous l'aurez compris le plugin ne peut rien sans le bon sketch (version accompagnant la mise à jour en cours) correctement flashé sur l'Arduino connecté. Pour une utilisation simple, sans besoin de personnalisation, le plugin vous propose un flash direct depuis son interface de réglage. Si vous désirez modifier les délais d’actualisation, les deltas de changement de valeur avant envoi ou ajouter vos options il vous sera nécessaire de passer par L’ArduinoIDE.
